### ISSUE TITLE
Uninstall Kepler doesn't remove clusterroles, rolebindings and scc on OpenShift

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#90] opened 2023-07-12 12:42 UTC
When the Kepler instance is created it creates the appropriate cluster role, role bindings, SCC, and service accounts required by the exporter to run. When we uninstall the instance it removes the SA from the deployed namespace but doesn't remove cluster roles, cluster role bindings, and SCC. The removal of these also doesn't happen when we uninstall the Kepler operator itself from the cluster.

Steps to reproduce:
* Deploy Kepler Operator via Operator hub on OpenShift.
* Create a Kepler Instance(It can be inside the `openshift-operators` namespace or different)
* Wait for daemonset's to come up.
* Check that the cluster roles, cluster role bindings, service account, and securitycontextconstraints are created.
* Delete the Kepler Instance/Operator from the console UI.

I think the removal of cluster roles, cluster role bindings, service account, and securitycontextconstraints should be handled by the Operator

**Comment by husky-parul** [comment] 2023-07-12 14:38
@vprashar2929 this is strange. Because `namespaced` based resources gets deleted when we uninstall the operator. We've faced similar issues with `PVCs` in the past and the fix was to include the PVCs in the [kepler finalizers. ](https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/controllers/kepler_controller.go#L117)
Maybe we can include the `scc, cluster roles, cluster role bindings and service account` too. 

Before that can we confirm if this is an expected behavior or that we have missed some `operator-sdk` implementation post operator uninstall.

@sthaha any idea?

**Comment by sthaha** [comment] 2023-07-12 23:52
> When the Kepler instance is created it creates the appropriate cluster role, role bindings, SCC, and service accounts required by the exporter to run. When we uninstall the instance it removes the SA from the deployed namespace but doesn't remove cluster roles, cluster role bindings, and SCC.

This is a bug which can fixed by using `ownerReferences` 
@husky-parul ☝️

>  The removal of these also doesn't happen when we uninstall the Kepler operator itself from the cluster.

This isn't a bug and is the expected behaviour when **any** operator is uninstalled. 
@vprashar2929

**Comment by sthaha** [comment] 2023-07-14 09:07
@husky-parul could you please shed some light on the use of finalizers ? 

> . Because namespaced based resources gets deleted when we uninstall the operator 

Uninstalling the operator should not delete the kepler CR and AFAIK should not affect any running kepler instances. 
Based in my limited knowledge of the operator, I don't think we need finalizers . 
Can you please help  me understand the scenario that led to us adding finalizers so that I can try that on a cluster ?

**Comment by vprashar2929** [comment] 2023-07-17 17:31
Some of my observations related to this issue:

On Kepler-Operator deployment:
* Kepler CRD gets installed
* Kepler CSV gets installed
* clusterrolebindings for Kepler-operator get configured
* clusterroles for Kepler-operator get configured

On Kepler Instance creation:
* clusterroles for Kepler get configured
* Kepler-SCC gets configured

On removal of Kepler Instance: Clusterroles and Kepler-SCC are still available on the cluster

On removal of Kepler-Operator:
* Kepler CSV gets removed
* clusterrole for Kepler-operator gets removed
* clusterrolebindings for Kepler-operator get removed

**Comment by acornett21** [comment] 2023-07-21 17:00
If this operator is creating an SCC, ClusterRole, ClusterRoleBinding it needs to use finalizers and manually cleanup these resources on it's own. This is due to the fact that `Namespaced` resources ie the Kepler CR, can not `own` a `ClusterScoped` resource. More on that relationship can be found [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/)

Specifically this section.
```
In v1.20+, if the garbage collector detects an invalid cross-namespace ownerReference, or a cluster-scoped dependent with an ownerReference referencing a namespaced kind, a warning Event with a reason of OwnerRefInvalidNamespace and an involvedObject of the invalid dependent is reported. You can check for that kind of Event by running kubectl get events -A --field-selector=reason=OwnerRefInvalidNamespace.
```

The use case may differ for this operator, ie are multiple `Kepler` CR's allowed or not, but [here](https://github.com/redhat-openshift-ecosystem/operator-certification-operator/blob/main/controllers/operatorpipeline_controller.go#L78-L121) is an example of what managing those resources look like. Hopefully this helps this discussion, and is not a distraction.

**Comment by husky-parul** [comment] 2023-07-21 17:20
@acornett21 Thank you for your comments. We have been discussing this. 
We releazied the issue with owner reference. for e.g.

```
oc get ds kepler-exporter -o jsonpath='{.metadata.ownerReferences}'

[{"apiVersion":"kepler.system.sustainable.computing.io/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"Kepler","name":"kepler","uid":"5d9240e1-4ad3-4d14-add6-
dc8423dd0501"}]
```

But for clusterrole and clusterrolebindings I get owner reference as empty

```
oc get clusterrolebinding kepler-clusterrole-binding -o jsonpath='{.metadata.ownerReferences}'
```

After initial brainstorming this was our conclusion.

This brings us to two options to try:
1. Change Kepler CR to clusterscope and see if the ownerrefernce is getting set
2. If option 1 doesn't fix this we will have to implement finalizers.

**Closed** 2023-07-27 01:50 UTC
Labels: bug
